### ISSUE TITLE
Model load error

### ISSUE THREAD

**Issue by Ayyappa44488** [SkyworkAI/Vitron#18]
I am getting the below error when i am trying to load the model from the checkpoints file and i am using torch 2.1.0 only
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tg0001/anaconda3/envs/vitron1/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/tg0001/anaconda3/envs/vitron1/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by anothersin** [comment]
same issue

**Comment by having-salt** [comment]
same issue
